### PR TITLE
Setup nav bar

### PR DESCRIPTION
**Pull request by Fernando426**
- This is my previous work as I am iterating the portal, I have made some changes since then to try to improve it and continue to work on it.

### CODE REVIEW

**Review by wayungi — COMMENTED** [review]
Hi @Fernando426 , 
image

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ 

- [ ] You have submitted a PR without a description.
desc


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Fernando426** [comment]
@wayungi   You tell me that it is marked as invalid, but you don't tell me what the error is! I need to know what the error is so I can try to fix it. I would appreciate it if you could explain to me what the error is and what I should repair? Thank you

**Comment by Fernando426** [comment]
@wayungi  You tell me that it is marked as invalid, but you don't tell me what the error is! I need to know what the error is so I can try to fix it. I would appreciate it if you could explain to me what the error is and what I should repair? Thank you

**Review by divinecharlotte — APPROVED** [review]
# Hello @Fernando426         😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 
### To Highlight 💯


- Descriptive readme👍 
- implementation of the required changes
 




## Congratulations! 🎉 



Cheers, and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
